### ISSUE TITLE
Thanks for the program!

### ISSUE THREAD

**Issue by mrkaban** [CodeDead/DeadLock#11]
Thank you very much for the quality program with such a great license!

Special thanks to the translators, including Leonid Gorokhov for the Russian translation.

Added a program to my website about free software ([link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C/%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5/deadlock-%D1%80%D0%B0%D0%B7%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2.html)).

Wishes:
1) run the program with administrator privileges.
2) integration with Windows Explorer immediately after installation, without having to turn it on in settings.

**Comment by CodeDead** [comment]
Hi mrkaban,

Thanks for the suggestions! Unfortunately as to number one, we recommend doing this only if the user is absolutely certain that a file is safe to be deleted. When the application always runs using administrative privileges, people run the risk of deleting files that are critical to their system.

As to your second suggestion: seems very reasonable. We'll include an option in the installer to enable this by default.

Thank you and we hope you have a great weekend

**Comment by CodeDead** [comment]
@mrkaban Apologies for the long delays in terms of replies. Apparantly these reply emails from Github were somehow marked as spam and we just noticed them while cleaning out the inbox.

In terms of the option to take over rights in the settings window, those are when you want DeadLock to automatically perform taking over a file or folder before 'unlocking' them.

The automatic language switch is a very interesting idea which should be implemented. Unfortunately DeadLock is currently no longer under active development and it has been a while since we last updated this application due to other projects taking over. However, as soon as there's time, rest assured that we will implement quite a few of your suggestions!
