### ISSUE TITLE
question(cli): unlock a folder

### ISSUE THREAD

**Issue by Kristinita** [CodeDead/DeadLock#12]
### 1. Summary

I read in [**documentation**](https://codedead.com/?page_id=822):

> You don’t have to open the GUI to unlock files or folders. You can jump straight into PowerShell or CMD to pass along arguments to DeadLock!

![DeadLock](https://i.imgur.com/dlVhCbo.png)

But I couldn't find, how I can unlock my folder without GUI.

### 2. Expected behavior

I have [**a project**](https://github.com/Kristinita/KristinitaPelican). If I edited files in project and ran build command, I can get `Permission denied` error. Therefore, before build command I unlock my project folder.

Currently, I need open GUI for unlocking. Every time it takes a time.

It would be nice unlock a folder via command line. So the user can add DeadLock command for unlocking at the beginning of build script → he wouldn't longer need manually unlocking actions.

But I can't find, how I can do it.

### 3. Data

I created `D:\SashaDebugging\KiraDeadLock` folder → I locked it:

![KiraDeadLock](https://i.imgur.com/7lDVw4k.png)

### 4. Expected behavior in similar apps

As [**LockHunter**](https://lockhunter.com/manual.htm). I run LockHunter command:

```text
lockhunter -u "D:\SashaDebugging\KiraDeadLock" -sm
```

Folder `D:\SashaDebugging\KiraDeadLock` successfully unlocked.

It would be nice to have similar behavior for DeadLock.

### 5. Not helped

I couldn't find answer to my question in:

1. DeadLock 1.4 Help documentation
1. Deadlock menu items
1. `deadlock --help`
1. Official site

Thanks.

**Comment by CodeDead** [comment]
Hi there @Kristinita 

The commandline interface at this time is nothing more than a way to pass startup arguments to DeadLock. This means that any and all files / folders that you pass in as arguments to the application will simply be opened in the user interface. We have plans to increase the functionality and documentation in regards to this feature (similar to say LockHunter), but as of right now DeadLock is no longer under active development due to other projects taking over. When there's time, rest assured that this will be addressed appropriately!

Kind regards
