### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Luckz** [CodeDead/DeadLock#14]
![image](https://user-images.githubusercontent.com/224748/85331423-604ecf00-b4d6-11ea-9a30-9284a2a3238d.png)

Not sure why.

Same happens trying to install it via scoop (which for some reason runs the installer, as admin and all).

**Comment by CodeDead** [comment]
Does your system have enough RAM available?

It looks like Inno Setup is warning you that your computer does not have the required resources available to actually run the installer.

You might want to try closing some applications to free up available memory and see if that does the trick.

**Comment by Luckz** [comment]
Maybe it's from the dark ages and doesn't understand 32GB RAM?
It worked with the Inno Installer unpacker. Thanks for saying it was Inno Setup.

**Comment by CodeDead** [comment]
Odd behaviour indeed, although the current build is, unfortunately, quite old. It's possible that on some systems, the older Inno Setup build might not work correctly. Very hard to debug.

Newer versions of Inno Setup might not have this problem. Closing this issue though, since you've managed to resolve it!
