### ISSUE TITLE
Maintainability: Migrate projects to SDK-style csproj

### ISSUE THREAD

**Issue by BinToss** [CodeDead/DeadLock#20]

**Comment by CodeDead** [comment]
A deadlock .NET library is now available on NuGet. It is awaiting approval but should be available on NuGet soon. The repo can be found here:
https://github.com/CodeDead/deadlock-dotnet-sdk

As for the User-interface side of things, I have decided to migrate the desktop application to Tauri and utilize Rust for the Windows API calls instead of .NET in addition to a React frontend written entirely in JavaScript.

This will produce modern code, with a very tiny binary that does not require .NET at all. This should close this problem. I would recommend discussing everything in regards to the .NET library here:
https://github.com/CodeDead/deadlock-dotnet-sdk
